// <auto-generated />
using System;
using Library.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410202346_newMigration")]
    partial class newMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Web.Core.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98001",
                            Email = "alice.johnson@library.com",
                            EmailConfirmed = true,
                            FullName = "Alice Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE.JOHNSON@LIBRARY.COM",
                            NormalizedUserName = "ALICE.JOHNSON",
                            PhoneNumber = "01000000001",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db001",
                            TwoFactorEnabled = false,
                            UserName = "alice.johnson"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98002",
                            Email = "bob.smith@library.com",
                            EmailConfirmed = true,
                            FullName = "Bob Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.SMITH@LIBRARY.COM",
                            NormalizedUserName = "BOB.SMITH",
                            PhoneNumber = "01000000002",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db002",
                            TwoFactorEnabled = false,
                            UserName = "bob.smith"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98003",
                            Email = "carla.davis@library.com",
                            EmailConfirmed = true,
                            FullName = "Carla Davis",
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLA.DAVIS@LIBRARY.COM",
                            NormalizedUserName = "CARLA.DAVIS",
                            PhoneNumber = "01000000003",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db003",
                            TwoFactorEnabled = false,
                            UserName = "carla.davis"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98004",
                            Email = "david.brown@library.com",
                            EmailConfirmed = true,
                            FullName = "David Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID.BROWN@LIBRARY.COM",
                            NormalizedUserName = "DAVID.BROWN",
                            PhoneNumber = "01000000004",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db004",
                            TwoFactorEnabled = false,
                            UserName = "david.brown"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98005",
                            Email = "eva.wilson@library.com",
                            EmailConfirmed = true,
                            FullName = "Eva Wilson",
                            LockoutEnabled = false,
                            NormalizedEmail = "EVA.WILSON@LIBRARY.COM",
                            NormalizedUserName = "EVA.WILSON",
                            PhoneNumber = "01000000005",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db005",
                            TwoFactorEnabled = false,
                            UserName = "eva.wilson"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98006",
                            Email = "frank.miller@library.com",
                            EmailConfirmed = true,
                            FullName = "Frank Miller",
                            LockoutEnabled = false,
                            NormalizedEmail = "FRANK.MILLER@LIBRARY.COM",
                            NormalizedUserName = "FRANK.MILLER",
                            PhoneNumber = "01000000006",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db006",
                            TwoFactorEnabled = false,
                            UserName = "frank.miller"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7e9b7c8e-f8f5-4ec7-88e1-01fc8cb98007",
                            Email = "grace.lee@library.com",
                            EmailConfirmed = true,
                            FullName = "Grace Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "GRACE.LEE@LIBRARY.COM",
                            NormalizedUserName = "GRACE.LEE",
                            PhoneNumber = "01000000007",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f8e2a9a2-c93f-4dbf-a0f9-13f4739db007",
                            TwoFactorEnabled = false,
                            UserName = "grace.lee"
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Award-winning fiction writer.",
                            Name = "Nora Allen"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Researcher in applied sciences.",
                            Name = "Samir Hassan"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Historian focused on modern history.",
                            Name = "Linda Carter"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Software architect and technical author.",
                            Name = "Omar Farouk"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Philosophy lecturer and essayist.",
                            Name = "Hana Youssef"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Biographer of notable leaders.",
                            Name = "James Walker"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Art critic and curator.",
                            Name = "Mia Chen"
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Img")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A contemporary fiction novel.",
                            Img = "images/books/silent-path.jpg",
                            IsDeleted = false,
                            Price = 120.00m,
                            Title = "The Silent Path"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Practical science concepts for everyone.",
                            Img = "images/books/physics-daily-life.jpg",
                            IsDeleted = false,
                            Price = 150.00m,
                            Title = "Physics in Daily Life"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "A journey through important historical events.",
                            Img = "images/books/echoes-past.jpg",
                            IsDeleted = false,
                            Price = 135.00m,
                            Title = "Echoes of the Past"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Guide to building scalable web apps.",
                            Img = "images/books/web-engineering.jpg",
                            IsDeleted = false,
                            Price = 220.00m,
                            Title = "Modern Web Engineering"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "An introduction to core philosophy topics.",
                            Img = "images/books/questions-meaning.jpg",
                            IsDeleted = false,
                            Price = 140.00m,
                            Title = "Questions of Meaning"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Biography of an influential innovator.",
                            Img = "images/books/life-pioneer.jpg",
                            IsDeleted = false,
                            Price = 160.00m,
                            Title = "Life of a Pioneer"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Understanding art movements and styles.",
                            Img = "images/books/seeing-colors.jpg",
                            IsDeleted = false,
                            Price = 145.00m,
                            Title = "Seeing Through Colors"
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 7
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Art"
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.Copy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowToRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Copies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowToRental = true,
                            BookId = 1,
                            Name = "Copy-001"
                        },
                        new
                        {
                            Id = 2,
                            AllowToRental = true,
                            BookId = 1,
                            Name = "Copy-002"
                        },
                        new
                        {
                            Id = 3,
                            AllowToRental = true,
                            BookId = 1,
                            Name = "Copy-003"
                        },
                        new
                        {
                            Id = 4,
                            AllowToRental = true,
                            BookId = 1,
                            Name = "Copy-004"
                        },
                        new
                        {
                            Id = 5,
                            AllowToRental = true,
                            BookId = 2,
                            Name = "Copy-005"
                        },
                        new
                        {
                            Id = 6,
                            AllowToRental = true,
                            BookId = 2,
                            Name = "Copy-006"
                        },
                        new
                        {
                            Id = 7,
                            AllowToRental = true,
                            BookId = 2,
                            Name = "Copy-007"
                        },
                        new
                        {
                            Id = 8,
                            AllowToRental = true,
                            BookId = 2,
                            Name = "Copy-008"
                        },
                        new
                        {
                            Id = 9,
                            AllowToRental = true,
                            BookId = 3,
                            Name = "Copy-009"
                        },
                        new
                        {
                            Id = 10,
                            AllowToRental = true,
                            BookId = 3,
                            Name = "Copy-010"
                        },
                        new
                        {
                            Id = 11,
                            AllowToRental = true,
                            BookId = 3,
                            Name = "Copy-011"
                        },
                        new
                        {
                            Id = 12,
                            AllowToRental = true,
                            BookId = 3,
                            Name = "Copy-012"
                        },
                        new
                        {
                            Id = 13,
                            AllowToRental = true,
                            BookId = 4,
                            Name = "Copy-013"
                        },
                        new
                        {
                            Id = 14,
                            AllowToRental = true,
                            BookId = 4,
                            Name = "Copy-014"
                        },
                        new
                        {
                            Id = 15,
                            AllowToRental = true,
                            BookId = 4,
                            Name = "Copy-015"
                        },
                        new
                        {
                            Id = 16,
                            AllowToRental = true,
                            BookId = 4,
                            Name = "Copy-016"
                        },
                        new
                        {
                            Id = 17,
                            AllowToRental = true,
                            BookId = 5,
                            Name = "Copy-017"
                        },
                        new
                        {
                            Id = 18,
                            AllowToRental = true,
                            BookId = 5,
                            Name = "Copy-018"
                        },
                        new
                        {
                            Id = 19,
                            AllowToRental = true,
                            BookId = 5,
                            Name = "Copy-019"
                        },
                        new
                        {
                            Id = 20,
                            AllowToRental = true,
                            BookId = 5,
                            Name = "Copy-020"
                        },
                        new
                        {
                            Id = 21,
                            AllowToRental = true,
                            BookId = 6,
                            Name = "Copy-021"
                        },
                        new
                        {
                            Id = 22,
                            AllowToRental = true,
                            BookId = 6,
                            Name = "Copy-022"
                        },
                        new
                        {
                            Id = 23,
                            AllowToRental = true,
                            BookId = 6,
                            Name = "Copy-023"
                        },
                        new
                        {
                            Id = 24,
                            AllowToRental = true,
                            BookId = 6,
                            Name = "Copy-024"
                        },
                        new
                        {
                            Id = 25,
                            AllowToRental = true,
                            BookId = 7,
                            Name = "Copy-025"
                        },
                        new
                        {
                            Id = 26,
                            AllowToRental = true,
                            BookId = 7,
                            Name = "Copy-026"
                        },
                        new
                        {
                            Id = 27,
                            AllowToRental = true,
                            BookId = 7,
                            Name = "Copy-027"
                        },
                        new
                        {
                            Id = 28,
                            AllowToRental = true,
                            BookId = 7,
                            Name = "Copy-028"
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.CopyRental", b =>
                {
                    b.Property<int>("CopyId")
                        .HasColumnType("int");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.HasKey("CopyId", "RentalId");

                    b.HasIndex("RentalId");

                    b.ToTable("CopyRentals", (string)null);

                    b.HasData(
                        new
                        {
                            CopyId = 1,
                            RentalId = 1
                        },
                        new
                        {
                            CopyId = 2,
                            RentalId = 2
                        },
                        new
                        {
                            CopyId = 3,
                            RentalId = 3
                        },
                        new
                        {
                            CopyId = 4,
                            RentalId = 4
                        },
                        new
                        {
                            CopyId = 5,
                            RentalId = 5
                        },
                        new
                        {
                            CopyId = 6,
                            RentalId = 6
                        },
                        new
                        {
                            CopyId = 7,
                            RentalId = 7
                        });
                });

            modelBuilder.Entity("Library.Web.Core.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 25.00m,
                            ApplicationUserId = 1,
                            DueAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 30.00m,
                            ApplicationUserId = 2,
                            DueAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 35.00m,
                            ApplicationUserId = 3,
                            DueAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 28.00m,
                            ApplicationUserId = 4,
                            DueAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 26.00m,
                            ApplicationUserId = 5,
                            DueAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Amount = 32.00m,
                            ApplicationUserId = 6,
                            DueAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 29.00m,
                            ApplicationUserId = 7,
                            DueAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "0d4e27db-c6b4-4b22-b17e-8dc6c81cb101",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "0d4e27db-c6b4-4b22-b17e-8dc6c81cb102",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Library.Web.Core.Models.Book", b =>
                {
                    b.HasOne("Library.Web.Core.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Library.Web.Core.Models.BookAuthor", b =>
                {
                    b.HasOne("Library.Web.Core.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Web.Core.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Copy", b =>
                {
                    b.HasOne("Library.Web.Core.Models.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Library.Web.Core.Models.CopyRental", b =>
                {
                    b.HasOne("Library.Web.Core.Models.Copy", "Copy")
                        .WithMany("CopyRentals")
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.Web.Core.Models.Rental", "Rental")
                        .WithMany("CopyRentals")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Copy");

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Rental", b =>
                {
                    b.HasOne("Library.Web.Core.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Rentals")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Library.Web.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Library.Web.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Web.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Library.Web.Core.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library.Web.Core.Models.ApplicationUser", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Copy", b =>
                {
                    b.Navigation("CopyRentals");
                });

            modelBuilder.Entity("Library.Web.Core.Models.Rental", b =>
                {
                    b.Navigation("CopyRentals");
                });
#pragma warning restore 612, 618
        }
    }
}
